name: Terraform

on:
  push:
    branches: [main]
    paths:
      - 'environments/**'
      - 'modules/**'
      - '.github/workflows/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        type: choice
        options:
          - dev
          - prod
          - global
      action:
        description: 'What to run?'
        required: true
        type: choice
        options:
          - apply
          - destroy
          - unlock
      lock_id:
        description: 'Terraform lock ID (only for unlock)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION_DEV: us-east-2
  AWS_REGION_PROD: us-east-1
  AWS_REGION_GLOBAL: us-east-1

jobs:
  lint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install actionlint
        run: |
          curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
      - name: Run actionlint
        run: ./actionlint

  changes:
    name: Detect changes
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.filter.outputs.dev }}
      prod: ${{ steps.filter.outputs.prod }}
      global: ${{ steps.filter.outputs.global }}
    steps:
      - uses: actions/checkout@v4
      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dev:
              - "environments/dev/**"
              - "modules/**"
            prod:
              - "environments/prod/**"
              - "modules/**"
            global:
              - "environments/global/**"
              - "modules/**"

  # -----------------------------
  # PLAN jobs (on push only)
  # -----------------------------
  dev-plan:
    name: Dev - Plan
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.dev == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::660830512266:role/iac-infra
          aws-region: ${{ env.AWS_REGION_DEV }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=environments/dev init -reconfigure

      - name: Terraform validate
        run: terraform -chdir=environments/dev validate

      - name: Terraform plan (save)
        run: terraform -chdir=environments/dev plan -out=tfplan -no-color -input=false -lock-timeout=5m

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: dev-tfplan
          path: environments/dev/tfplan
          if-no-files-found: error

  prod-plan:
    name: Prod - Plan
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.prod == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/prod
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::660830512266:role/iac-infra
          aws-region: ${{ env.AWS_REGION_PROD }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=environments/prod init -reconfigure

      - name: Terraform validate
        run: terraform -chdir=environments/prod validate

      - name: Terraform plan (save)
        run: terraform -chdir=environments/prod plan -out=tfplan -no-color -input=false -lock-timeout=5m

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: prod-tfplan
          path: environments/prod/tfplan
          if-no-files-found: error

          # loucuras acontecem por aqui
  global-plan:
    name: Global - Plan
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.global == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/global
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::660830512266:role/iac-infra
          aws-region: ${{ env.AWS_REGION_GLOBAL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=environments/dev init -reconfigure

      - name: Terraform validate
        run: terraform -chdir=environments/dev validate

      - name: Terraform plan (save)
        run: terraform -chdir=environments/dev plan -out=tfplan -no-color -input=false -lock-timeout=5m

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: dev-tfplan
          path: environments/dev/tfplan
          if-no-files-found: error

  # -----------------------------
  # APPLY / DESTROY (manual only)
  # -----------------------------
  run:
    name: Manual - ${{ inputs.action }} (${{ inputs.environment }})
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    # ðŸ” This triggers GitHub Environment approvals (dev/prod/global)
    environment: ${{ inputs.environment }}

    # ðŸš¦ Prevent concurrent state mutations per environment
    concurrency:
      group: terraform-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Set env vars
        id: vars
        shell: bash
        run: |
          if [ "${{ inputs.environment }}" = "dev" ]; then
          {
          echo "WORKDIR=environments/dev"
          echo "REGION=${{ env.AWS_REGION_DEV }}"
          echo "TFPLAN=dev-tfplan"
          } >> "$GITHUB_OUTPUT"
          elif [ "${{ inputs.environment }}" = "prod" ]; then
          {
          echo "WORKDIR=environments/prod"
          echo "REGION=${{ env.AWS_REGION_PROD }}"
          echo "TFPLAN=prod-tfplan"
          } >> "$GITHUB_OUTPUT"
          else
          {
          echo "WORKDIR=environments/global"
          echo "REGION=${{ env.AWS_REGION_GLOBAL }}"
          echo "TFPLAN=global-tfplan"
          } >> "$GITHUB_OUTPUT"
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::660830512266:role/iac-infra
          aws-region: ${{ steps.vars.outputs.REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init (upgrade providers)
        working-directory: ${{ steps.vars.outputs.WORKDIR }}
        run: terraform init -upgrade -reconfigure

      - name: Terraform force-unlock
        if: inputs.action == 'unlock'
        working-directory: ${{ steps.vars.outputs.WORKDIR }}
        run: terraform force-unlock -force "${{ inputs.lock_id }}"

      - name: Terraform plan
        if: inputs.action != 'unlock'
        working-directory: ${{ steps.vars.outputs.WORKDIR }}
        run: terraform plan -no-color -input=false -lock-timeout=5m

      - name: Terraform apply
        if: inputs.action == 'apply'
        working-directory: ${{ steps.vars.outputs.WORKDIR }}
        run: terraform apply -auto-approve -lock-timeout=5m

      - name: Terraform destroy
        if: inputs.action == 'destroy'
        working-directory: ${{ steps.vars.outputs.WORKDIR }}
        run: terraform destroy -auto-approve -lock-timeout=5m
